# Basic site config
baseURL = "https://robincarswell.com"
languageCode = "en-gb"
DefaultContentLanguage = "en-gb"
theme = "anatole"
summarylength = 20
enableEmoji = true
enableRobotsTXT = true
displayMode = "dark"


# Site content
[params]
title = "Robin Carswell"
author = "Robin Carswell"
description = "I do technology, product and business strategy projects in the UK. I spend my spare time on tech for good and venturebuilding."
profilePicture = "images/rjc.png"
copyright = "{{ YEAR }} Robin Carswell"


# Analytics and Plugins
#disqusShortname = ""
gtagId = "G-9F57FFB75P"

