# Basic site config
baseURL = "https://robincarswell.com"
languageCode = "en-gb"
DefaultContentLanguage = "en-gb"
theme = "anatole"
summarylength = 20
enableEmoji = true
enableRobotsTXT = true
displayMode = "dark"


# Site content
[params]
title = "Robin Carswell"
author = "Robin Carswell"
description = "I do technology, product and business strategy projects in the UK. I spend my spare time on tech for good and venturebuilding."
profilePicture = "images/rjc.png"
copyright = "{{ YEAR }} Robin Carswell"
favicon = "/favicon/"
mainSections = ["posts"]

# Analytics and Plugins
# disqusShortname = ""
gtagId = "G-9F57FFB75P"


# Socials

[[params.socialIcons]]
icon = "fab fa-linkedin"
title = "Linkedin"
url = "https://uk.linkedin.com/in/robincarswell"

[[params.socialIcons]]
icon = "fab fa-github"
title = "Github"
url = "https://github.com/rjc123"

[[params.socialIcons]]
icon = "fab fa-bluesky"
title = "Bluesky"
url = "https://bsky.app/profile/robincarswell.bsky.social"

[[params.socialIcons]]
icon = "fas fa-envelope"
title = "e-mail"
url = "mailto:hello@robincarswell.com"

# Menus

[menus]
  [[menus.main]]
    name = 'Home'
    pageRef = '/'
    weight = 10
  [[menus.main]]
    name = 'Posts'
    pageRef = '/posts'
    weight = 20
  [[menus.main]]
    name = 'Startups'
    pageRef = '/startups'
    weight = 30
  [[menus.main]]
    name = 'Twitter'
    pageRef = '/twitter'
    weight = 40

