theme = "anatole"
baseURL = "http://rjc123.github.com/robincarswell.com"
languageCode = "en-gb"

[params]
title = "I'm Robin Carswell"
author = "Robin Carswell"
description = "Call me RJ"
profilePicture = "images/robin-symbol.png"
